packaging_format = 2

id = "firefly-iii-di"
name = "Firefly III Importer"
description.en = "Firefly III Data Importer"
description.fr = "Importateur de données Firefly III"

version = "1.5.2~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://docs.firefly-iii.org/data-importer/"
admindoc = "https://docs.firefly-iii.org/data-importer/how-to-use/"
code = "https://github.com/firefly-iii/data-importer"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fiidi"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        url = "https://github.com/firefly-iii/data-importer/releases/download/v1.5.2/DataImporter-v1.5.2.tar.gz"
        sha256 = "0cbc821f9052cf03cebad2870a58527986a1d36077bfa60829c99f00b9919ca3"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-xml php8.3-bcmath"
